spring:
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/rest_board
    username: root
    password: root
  security:
    user:
      name: user
      password: 1234
  jwt:
    secret: secretKey

logging:
  level:
    org:
      springframework:
        jdbc: debug
    board:
      mapper: trace

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml


