@startuml
actor User

User -> BoardController: DELETE /post/{id}
activate BoardController

BoardController -> BoardService: DeleteBoardDto 맵핑 및 유효성 체크
activate BoardService

BoardService -> BoardMapper: 게시글 삭제
activate BoardMapper

BoardMapper -> DataBase: 게시글 삭제 쿼리 실행

BoardMapper --> BoardService: 게시글 존재 여부
deactivate BoardMapper

alt Board does not exist
    BoardService --> BoardController: 존재하지 않는 게시글
    deactivate BoardService
    BoardController --> User: ResponseEntity Status: 404

else Board exists
    alt User is not owner
        BoardService --> BoardController: 게시글 삭제 권한 없음
        BoardController --> User: ResponseEntity Status: 403
    else User is owner
        BoardService -> BoardMapper: 게시글 댓글수 확인
        activate BoardMapper
        BoardMapper -> DataBase: 게시글 댓글수 조회
        activate DataBase

        DataBase --> BoardMapper: 게시글 댓글수 반환
        deactivate DataBase
        BoardMapper --> BoardService: Comments Count
        deactivate BoardMapper

        alt Comments exist
            BoardService -> BoardMapper: 게시글 댓글 삭제
            activate BoardMapper
            BoardMapper -> DataBase: 게시글 댓글 삭제 쿼리 실행
            deactivate BoardMapper
        end

        BoardService --> BoardController: 게시글 삭제 성공
        BoardController --> User: ResponseEntity Status: 200
    end
end
deactivate BoardController

@enduml
