@startuml

actor User

User -> JwtAuthorizationFilter: 토큰 유효성 체크
activate JwtAuthorizationFilter
deactivate JwtAuthorizationFilter

User -> JwtAuthenticationFilter: POST /login (username, password)
activate JwtAuthenticationFilter

JwtAuthenticationFilter -> AuthenticationManager: 인증 시도
activate AuthenticationManager

AuthenticationManager -> AuthenticationProvider: 인증 요청 처리
activate AuthenticationProvider

alt 인증 성공
    AuthenticationProvider --> AuthenticationManager: 인증 성공
    deactivate AuthenticationProvider
    AuthenticationManager --> JwtAuthenticationFilter: 인증 객체 전달
    JwtAuthenticationFilter -> JwtTokenService: JWT 토큰 생성 요청
    activate JwtTokenService
    JwtTokenService --> JwtAuthenticationFilter: JWT 토큰 반환
    deactivate JwtTokenService
    JwtAuthenticationFilter --> User: ResponseEntity Status: 200 (JWT 토큰 포함)

else 인증 실패
    AuthenticationProvider --> AuthenticationManager: 인증 실패
    deactivate AuthenticationProvider
    AuthenticationManager --> JwtAuthenticationFilter: 인증 실패
    JwtAuthenticationFilter --> User: ResponseEntity Status: 401
end

deactivate AuthenticationManager
deactivate JwtAuthenticationFilter

@enduml