@startuml
actor User

User -> MemberController: POST /sign-up
activate MemberController

MemberController -> MemberService: signUpDto 맵핑 및 유효성 체크
activate MemberService

MemberService -> UserMapper: Username 중복 체크
activate UserMapper

UserMapper -> DataBase : Username 중복 여부 쿼리 실행
activate DataBase

DataBase --> UserMapper: Boolean
deactivate DataBase
UserMapper --> MemberService: true/false
deactivate UserMapper

alt Username exists
    MemberService --> MemberController: 이미 존재하는 로그인 ID
    MemberController --> User: ResponseEntity Status: 400
    deactivate MemberService

else not exists
    MemberService -> UserMapper: Email 중복 체크
    activate UserMapper
    UserMapper -> DataBase : Email 중복 여부 쿼리 실행
    activate DataBase

    DataBase --> UserMapper: Boolean
    deactivate DataBase

    UserMapper --> MemberService: true/false
    deactivate UserMapper

    alt Email exists
        MemberService --> MemberController: 이미 존재하는 Email
        deactivate MemberService
        MemberController --> User: ResponseEntity Status: 400

    else not exists
        MemberService -> UserMapper: 회원 저장
        UserMapper -> DataBase: 회원 저장 쿼리 실행

        MemberService --> MemberController: 회원가입 성공
        deactivate MemberService
        MemberController --> User: ResponseEntity Status: 200
    end
end

deactivate MemberController

@enduml
